### ISSUE TITLE
My profile appears twice in the leaderboard

### ISSUE THREAD

**Issue by PumpkingWok** [gitcoinco/web#2195]
**Describe the bug**
- My profile (PumpkingWok as my github username) appears twice in the leaderboard https://gitcoin.co/leaderboard , right now on position 59 (with seven bounties) and 147 (with one bounty). In position 147 the profile name is wrong, `pumpkingwok` instead of `PumpkingWok`

- In my profile page the position in the ranking reflects the last one, number 147, which one with wrong name.

- Few days ago I have received a tip, that it seems to be equivalent of total amount in usd of the only bounty in position 147. Is it possible that they edited the wrong profile name when sent a tip to me ? I don't know because I have never created a bounty or sent a tip.

**To Reproduce**
Leaderboard -> https://gitcoin.co/leaderboard
My profile -> https://gitcoin.co/profile/PumpkingWok

**Comment by PixelantDesign** [comment]
Thanks for reporting these @PumpkingWok!

**Comment by owocki** [comment]
probably makes sense to normalize the capitalization of the usernames when we run `assemble_leaderbords`

**Comment by PumpkingWok** [comment]
Hi there,
I have encountered the same issue few days ago, my gitcoin profile appears twice in leaderboard again.
 It has been caused by inserting wrong capital letters in my gitcoin username using advanced payout, i think.
Thanks in advance.

**Comment by thelostone-mc** [comment]
Seems this has been resolved 🙌

**Comment by PumpkingWok** [comment]
Hi @thelostone-mc,
Yes, it has been resolved, thank you very much.

**Comment by PumpkingWok** [comment]
Hi there,
Unfortunately my leaderboard position is getting wrong again, i think it was caused by a tip sent to me using a wrong gitcoin profile name (caused by capital letters), and my profile appears twice in leaderboard.
https://gitcoin.co/profile/PumpkingWok -> it reflects the position # 352 but i think i'm in position # 30 more or less.
I think that the issue is back when the leaderboard has started to list only the top 25 position, before that i could see the right position in my profile.
Thanks in advance.

**Comment by PumpkingWok** [comment]
HI there ! Any news on it ? My leaderboard position is still wrong.
Apart from this, in my profile i can not see my github organizations. Do i need to import it in some way ? Thanks in advance !!

**Comment by owocki** [comment]
can you open up another ticket about your expectations about github organizations..?

> it reflects the position # 352 but i think i'm in position # 30 more or less.

note that the leaderboard only tracks work done in the last quarter.

**Comment by PumpkingWok** [comment]
Hi @owocki ,

Thank you very much for the reply, I did not know that the leaderboard keeps track only from last quarter. perfect, so my position should be correct.
I'm going to open a new issue regard the github organizations, thanks again.
